import wizards
from main_window_generic import MainWindowGeneric
from base_central_widget import BaseCentralWidget
from central_generic import CentralGeneric
from ide_generic import IDEGeneric
from tab_central_generic import TabCentralGeneric